apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calc-webapp
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: calc-webapp
    spec:
      containers:
      - image: mmelendez/calc-webapp:latest
        imagePullPolicy: Always
        name: calc-webapp
        ports:
          - containerPort: 8080
