apiVersion: extensions/v1beta1
kind: Deployment                                          
metadata:
  name: calc-frontend
spec:
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                  
    rollingUpdate: 
      maxUnavailable: 1                                  
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: calc-frontend                                  
    spec:
      containers:
        - image: mmelendez/calc-frontend:latest
          imagePullPolicy: Always                         
          name: calc-frontend
          ports:
            - containerPort: 80
