apiVersion: v1
kind: Service              
metadata:
  name: calc-frontend-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80        
  selector:                
    app: calc-frontend      
