apiVersion: v1
kind: Service              # 1
metadata:
  name: calc-frontend-lb
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: calc-frontend       # 7
